***Learning Matrix in the numpy***

In [6]:
import numpy as np

In [7]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
mat=np.array(x)

In [9]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
mat.sum(axis=0)

array([12, 15, 18])

In [11]:
mat.sum(axis=1)

array([ 6, 15, 24])

In [14]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
mat.ndim

2

In [16]:
mat.size

9

In [17]:
mat.shape

(3, 3)

In [19]:
mat.nbytes

36

ONE DIMENTION:- MAX AND MIN

In [24]:
import numpy as np

In [31]:
one=np.array([9,5,7,6,8,4,3,2,1])

In [32]:
one.argmin()

8

In [33]:
one.argmax()

0

In [34]:
one.argsort()

array([8, 7, 6, 5, 1, 3, 2, 4, 0], dtype=int64)

***Sorting for Matrix***

In [37]:
mat.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [38]:
mat.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [39]:
mat.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [41]:
mat.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [42]:
mat.argmax()

8