**Welcome to Python**


In [7]:
print("Hello World!!!")

Hello World!!!


In [5]:

import numpy as np
arr=np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


***Printing Array,size,shape and its datatype***

In [8]:
print(arr[1])

2


In [10]:
myarr=([78,97,45,78,95,23,np.int64])

In [13]:
print(myarr)
print(myarr[1])

[78, 97, 45, 78, 95, 23, <class 'numpy.int64'>]
97


****Maths operations***

In [16]:
print(myarr[0]+arr[1])

80


In [18]:
print(myarr[1]-arr[1])

95


In [19]:
print(myarr[3]*arr[2])

234


In [20]:
print(myarr[4]/arr[1])

47.5


In [21]:
print(myarr[5]-arr[2])

20


****Some special arrays****

In [28]:
zeros=np.zeros((2,5))

In [29]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
ones=np.ones((2,3))

In [31]:
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
ones.dtype

dtype('float64')

****Ranges****

In [34]:
rane=np.arange(3)

In [37]:
rane

array([0, 1, 2])

***Lanespace function is used to get eual space from start to end***

In [38]:
equalspace=np.linspace(1,10,5)

In [39]:
equalspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

***For random element we use empty(x,y) function where it gives random numbers in x*y matrix***

In [40]:
emp=np.empty((3,2))

In [41]:
emp

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
emparray=np.empty_like(arr)

In [43]:
emparray

array([1, 2, 3, 4, 5])

In [44]:
emparray1=np.empty_like(myarr)

In [45]:
emparray1


array([None, None, None, None, None, None, None], dtype=object)

****For Changing the shape ****

In [46]:
arr=np.arange(99)

In [47]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [48]:
shape=arr.reshape(11,9)

In [49]:
shape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [50]:
oldshape=arr.ravel()

In [51]:
oldshape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])